name: GCP over terraform

on: [push]

jobs:
  install-terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest

    steps:
      - uses: actions/checkout@v3

      - name: Check terraform
        run: |
          terraform -v

      - name: Setup terraform
        run: |
          cd "$GITHUB_WORKSPACE/gcp"
          terraform init

      - name: Run terraform
        run: |
          cd "$GITHUB_WORKSPACE/gcp"
          terraform plan
          terraform apply -auto-approve
    
      - name: Destroy terraform
        run: |
          cd "$GITHUB_WORKSPACE/gcp"
          terraform destroy -auto-approve