name: GCP over terraform

on: [push]

jobs:
  run-shell-command:
    runs-on:
      using: 'docker'
      image: 'hashicorp/terraform'
    steps:
#      - uses: actions/checkout@v3

      - name: Check terraform
        run: terraform -v

