name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3

      - name: Install terraform linter
        run: |
          tar xzf -C /usr/local/bin $GITHUB_WORKSPACE/paketi/config-lint_Linux_x86_64.tar.gz config-lint
          chmod +rx /usr/local/bin/config-lint
          config-lint -h
