name: GCP over terraform

on: [push]

jobs:
  install-terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest

    steps:
      - uses: actions/checkout@v3

      - name: Check terraform
        run: |
          terraform -v

#      - name: 'Authenticate to Google Cloud'
#        uses: 'google-github-actions/auth@v0'
#        with:
#          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - name: Setup terraform
        run: |
          cd "$GITHUB_WORKSPACE/gcp"
          terraform init
          pwd
          terraform validate main.tf

#      - name: Run terraform
#        run: |
