name: GCP over terraform

on: [push]
jobs:

  GCP-login:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest

    steps:
    - name: 'Check GCP'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Setup env'
      uses: 'actions/checkout@v3'
      
    - name: 'Check terraform'
      run: |
        terraform -v

    - name: 'Setup terraform'
      run: |
        cd "$GITHUB_WORKSPACE/gcp"
        terraform init

    - name: 'Run terraform'
      run: |
        cd "$GITHUB_WORKSPACE/gcp"
        terraform plan
        terraform apply -auto-approve
    
    - name: 'Destroy terraform'
      run: |
        cd "$GITHUB_WORKSPACE/gcp"
        terraform destroy -auto-approve