name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: echo command
        run: echo "Hello World"

      - name: multiline script
        run: |
          node -v
          npm -v

      - name: raspakovati paket
        run: |
          tar xzf /home/runner/work/actions-test/actions-test/paketi/config-lint_Linux_x86_64.tar.gz config-lint
          chmod +rx config-lint
