name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: raspakovati paket
        run: |
          mkdir /usr/local/bin/paket
          cd /usr/local/bin/paket
          curl -L https://github.com/Vrana030/actions-test/blob/main/paketi/config-lint_Linux_x86_64.tar.gz
          tar xzf config-lint_Linux_x86_64.tar.gz config-lint
          chmod +rx config-lint
