name: GCP over terraform

on: [push]
jobs:

  GCP-login:
    runs-on: ubuntu-latest

    steps:
    - name: 'Check GCP'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

  install-terraform:
    needs: GCP-login
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest

    steps:
      - name: 'Setup env'
        uses: 'actions/checkout@v3'
      
      - name: 'Check terraform'
        run: |
          terraform -v

      - name: 'Setup terraform'
        run: |
          cd "$GITHUB_WORKSPACE/gcp"
          terraform init

      - name: 'Run terraform'
        run: |
          cd "$GITHUB_WORKSPACE/gcp"
          gcloud auth activate-service-account github@electric-wave-315708.iam.gserviceaccount.com --key-file="/home/runner/work/actions-test/actions-test/gha-creds-a322a55c24d5e61b.json"
          terraform plan
          terraform apply -auto-approve
    
      - name: 'Destroy terraform'
        run: |
          cd "$GITHUB_WORKSPACE/gcp"
          terraform destroy -auto-approve