name: GCP over terraform

on: [push]

jobs:
  install-terraform:
    runs-on: ubuntu-latest
      container:
        image: hashicorp/terraform:latest

    steps:
#      - uses: actions/checkout@v3

      - name: Check terraform
        run: |
          terraform -v

