name: Wiz instalation

on: [push]
jobs:

  install-wiz:
    runs-on: ubuntu-latest
    container:
      image: wiziocli.azurecr.io/wizcli:latest

    steps:
      - name: 'Check wizcli'
        run: |
          docker run wiziocli.azurecr.io/wizcli:latest version