name: Wiz instalation

env:
 WIZ_IAC_SCAN_ID: ${{ secrets.WIZ_IAC_SCAN_ID }}
 WIZ_IAC_SCAN_SECRET: ${{ secrets.WIZ_IAC_SCAN_SECRET }}

on: [push]
jobs:

  install-wiz:
    runs-on: ubuntu-latest
    container:
      image: wiziocli.azurecr.io/wizcli:latest

    steps:
      - name: 'Wiz login'
        run: |
          auth --id=$WIZ_IAC_SCAN_ID --secret=$WIZ_IAC_SCAN_SECRET


    steps:
      - name: 'Check wizcli'
        run: |
          version
